// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Repositories;

namespace ToDoList.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181207233636_Associados")]
    partial class Associados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoList.Domain.Associated", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adress");

                    b.Property<string>("birthDate");

                    b.Property<string>("cep");

                    b.Property<string>("city");

                    b.Property<string>("email");

                    b.Property<string>("maritalStatus");

                    b.Property<string>("name");

                    b.Property<string>("uf");

                    b.HasKey("id");

                    b.ToTable("Associated");
                });

            modelBuilder.Entity("ToDoList.Domain.Dependente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("assid");

                    b.Property<string>("birthDate");

                    b.Property<string>("kinship");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("assid");

                    b.ToTable("Dependente");
                });

            modelBuilder.Entity("ToDoList.Domain.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoList.Domain.Dependente", b =>
                {
                    b.HasOne("ToDoList.Domain.Associated", "ass")
                        .WithMany("dep")
                        .HasForeignKey("assid");
                });
#pragma warning restore 612, 618
        }
    }
}
